ccflags-y                       += -DNV_DEBUG=0
obj-$(CONFIG_SND_TEGRA_SOC_PCM) += tegra_pcm.o
obj-$(CONFIG_SND_TEGRA_SOC_I2S) += tegra_i2s.o
obj-$(CONFIG_SND_TEGRA_SOC_IEC) += tegra_spdif.o
obj-${CONFIG_SND_SOC_WM8903}    += tegra_wired_jack.o tegra_soc_controls.o tegra_generic_codec.o tegra_soc_wm8903.o
obj-${CONFIG_SND_SOC_WM8753}    += tegra_wired_jack.o tegra_soc_controls.o tegra_generic_codec.o tegra_soc_wm8753.o
obj-${CONFIG_SND_SOC_ALC5624}   += tegra_generic_codec.o tegra_soc_alc5624.o
